apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: __APP__
  name: __APP__
  namespace: wing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: __APP__
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: __APP__
    spec:
      containers:
      - image: __IMAGE__
        imagePullPolicy: IfNotPresent
        name: __APP__
        ports:
        - containerPort: 80
          name: naport
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

